## Assignment 6

In [31]:
import numpy as np

### Set 1:

Create a 3×3 array of all True Boolean values

In [41]:
arr=np.full_like(np.arange(1,10).reshape(3,3),True, dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract odd numbers from an array

In [ ]:
arr=np.arange(1,13)
odd_mask=(arr%2==1)
odd_nums=arr[odd_mask]
odd_nums

array([ 1,  3,  5,  7,  9, 11])

Replace all odd numbers with -1

In [56]:
arr=np.arange(1,13)
odd_mask=(arr%2==1)
arr[odd_mask]=-1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12])

Reverse columns of a 2D array

In [67]:
print('original array:')
arr=np.arange(1,9).reshape(2,4)
print(arr)
arr=arr[:,::-1]
print('reversed array:')
print(arr)

original array:
[[1 2 3 4]
 [5 6 7 8]]
reversed array:
[[4 3 2 1]
 [8 7 6 5]]


Get indices of elements greater than 5 [hint: check where method of numpy]

In [70]:
arr=np.arange(1,8)
a1=np.where(arr>3)
print(a1)

(array([3, 4, 5, 6]),)


Access last row - last column

In [75]:
arr=np.arange(1,13).reshape(3,4)
print(arr)
print('\nlast-row-last-column:\n',arr[-1,-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

last-row-last-column:
 12


### Set 2:
Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]

In [92]:
arr=np.arange(1,13)
arr=np.sqrt(arr).reshape(3,4)
print(arr)

varr=np.clip(arr,0,1)
print(varr)

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Create a 5×5 array with 1 on border and 0 inside

Create a random array of 10×10: perform stats (min, max, mean, std)

Broadcast a 1D array over a 2D array [all possible scenarios]

Sort a 2D array by column 1 [hint: check method argsort()]

### Set 3:

Find common elements between two arrays [with and without using intersect1d]

Subtract row mean from each row of a 2D array

Given a 4×4 array, swap the first half rows with the second half rows

Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).

From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method).

### GeeksforGeeks

### [Power of 2](https://www.geeksforgeeks.org/problems/power-of-2-1587115620/1)

### [First and Last Occurrence](https://www.geeksforgeeks.org/problems/first-and-last-occurrences-of-x3116/1)

In [27]:
def find(arr, x):
        first_o=-1
        last_o=-1
        if x not in set(arr):
            return [-1,-1]
        for i in range(len(arr)):
            if arr[i]==x & first_o !=-1:
                print(i)
                first_o,last_o=i,i
            elif arr[i]==x:
                last_o=i
        return [first_o,last_o]

In [28]:
a=[6, 6, 6, 6, 7, 7, 7, 8]
find(a,8)

7


[7, 7]

In [29]:
def is_power_of_two_bitwise(n):
    """Checks if n is a power of 2 using the bitwise AND operation."""
    # Must be positive (n > 0) AND have exactly one bit set to 1
    return n > 0 and (n & (n - 1) == 0)